sudo: required #Travis ci requires the user to be with elevated permission

language: node_js
node_js:
    - "stable"
    
services: 
    - docker #Our use of travis ci needs an instance of docker to be running
    

before_install: #Things to do with your code on travis ci before running tests or deploying your code
    - docker build -t wilpat/sample-docker-react -f Dockerfile.dev . #Used the .dev dockerfile cos we need to run the tests in travis ci and the test image is in that .dev file

script:     
    - docker run -e CI=true wilpat/sample-docker-react npm run test -- --coverage

deploy: #This deploys the whole folder onto elasticbeanstalk so it's the production Dockerfile that would be used by elasticbeanstalk to startup this app
    provider: elasticbeanstalk
    region: "us-east-1" #region you selected when creating the elb application
    app: "react-application" #the aws elb app name
    env: "ReactApplication-env" #the aws elb app environment
    bucket_name: "elasticbeanstalk-us-east-1-965102668059" #s3 storage location for all apps deployed to this region
    bucket_path: "react-application" #name of the folder where this app you're targeting is located or going to exist
    on:
        branch: master #Only deploy when master branch is updated
    access_key_id: $AWS_ACCESS_KEY #Environment variable generated in IAM of AWS but stored in travis ci
    secret_acces_key: "$AWS_SECRET_KEY" # Another environment variable generated in IAM of AWS but stored in travis ci
